version: '3.8'

services:
  # MongoDB - Container já configurado conforme uso atual
  mongodb:
    image: mongo:latest
    container_name: newcashft-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Aplicação completa - Backend servindo o Frontend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newcashft-app
    restart: always
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/newcashft
      - JWT_SECRET=seu_jwt_secret
      - NODE_ENV=production
      # Garante que todas as contas (Principal, USD, EUR, USDT) sejam exibidas
      # E que as contas FT (60248, 60249) permaneçam exclusivas do admin
      - DISPLAY_ALL_ACCOUNTS=true
      - ADMIN_EXCLUSIVE_FT_ACCOUNTS=true
    depends_on:
      - mongodb

volumes:
  mongodb_data:
